### ISSUE TITLE
Why does this repo contain only 2 papers?

### ISSUE THREAD

**Issue by nbro** [numenta/htmpapers#9]
In the README file, you say

> This repository is currently under construction and will include the source code for all scripts used on Numenta's papers.

But, AFAIK, there have been more than 2 papers already published by Numenta. I am not sure why this would take so much time to do. The last commit to this repo was in November of last year.

**Comment by subutai** [comment]
Hi @nbro - the source code for all our papers is already available in our research repository: https://github.com/numenta/htmresearch. Almost all of our day to day research code is available there.

This repository is making sure everything is versioned and properly reproducible. This is taking a bit longer than expected for the older papers, but we recently fixed a numerical precision issue that was holding us up. We should have more papers appearing soon. For our newer papers, we are writing the code with this repository in mind so that it can be placed here sooner.

Note that the code for our anomaly detection papers are in the NAB repository, not here: https://github.com/numenta/NAB
